### ISSUE TITLE
Mouse movement escape codes are fed into the editor

### ISSUE THREAD

**Issue by jamesmunns** [Trangar/zettelkasten#30]
![output](https://user-images.githubusercontent.com/2097964/203033926-4ae2cd86-5602-470a-8e79-5ac0bdaa8a7c.gif)

Hey there! When using zettelkasten with nano + alacritty, I get escape codes inserted into the text editor window. This does not normally occur when I use nano directly. I've attached a gif of what this looks like.

Thanks for sharing, the menu system is SUPER slick! I love the feedback when changing the editor (showing whether the bin exists).

**Comment by VictorKoenders** [comment]
I wonder if it should disable the TUI modes that are enabled [here](https://github.com/Trangar/zettelkasten/blob/trunk/front/terminal/src/lib.rs#L46-L50) and disabled when the application closes [here](https://github.com/Trangar/zettelkasten/blob/trunk/front/terminal/src/lib.rs#L81-L87)

**Comment by jamesmunns** [comment]
I can give it a try! Let me pull down the repo and build.

**Comment by jamesmunns** [comment]
I can confirm that removing just the `EnableMouseCapture`/`DisableMouseCapture` lines seem to prevent the issue for me, removing the other modes caused problems :p.

Want me to open a PR for this? Or would you want to make it a runtime config or compile time feature?

**Comment by VictorKoenders** [comment]
A PR would be great, thanks! I'm assuming other editors also don't expect the parent program to capture the mouse inputs
